### ISSUE TITLE
Kubernetes Without Docker Runtime

### ISSUE THREAD

**Issue by bdsoha** [hardillb/nginx-proxy-avahi-helper#3]
Hello,

Have you had any experience using this with k8s that is not using Docker as a container runtime?

**Comment by hardillb** [comment]
This code explicitly uses the Docker API, but you probably want this version:

https://github.com/hardillb/k8s-ingress-to-avahi

**Comment by bdsoha** [comment]
Thanks for your quick response. 
I had a look at your other repo, but it is run from outside the cluster. It would be great to have the option of running it in the cluster with a ServiceAccount for authenticated access to the kube-api. 

Thanks.

**Comment by hardillb** [comment]
Feel free to submit a pull request to improve the project
